# Sobreescrituras para desarrollo local.
# Docker Compose lo aplica automáticamente encima de docker-compose.yml
services:
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
