"""add indexes on invoice foreign keys

Revision ID: 059cc7a5180f
Revises: a2b3c4d5e6f7
Create Date: 2026-03-20 15:42:28.513538

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "059cc7a5180f"
down_revision: Union[str, None] = "a2b3c4d5e6f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_invoices_agreement_id", "invoices", ["agreement_id"], unique=False)
    op.create_index("ix_invoices_audit_period_id", "invoices", ["audit_period_id"], unique=False)
    op.create_index("ix_invoices_folder_status_id", "invoices", ["folder_status_id"], unique=False)
    op.create_index("ix_invoices_service_type_id", "invoices", ["service_type_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_invoices_service_type_id", table_name="invoices")
    op.drop_index("ix_invoices_folder_status_id", table_name="invoices")
    op.drop_index("ix_invoices_audit_period_id", table_name="invoices")
    op.drop_index("ix_invoices_agreement_id", table_name="invoices")
    # ### end Alembic commands ###
