"""drop_unique_invoice_id_prefix

Revision ID: 7929537df5a9
Revises: db5ece233ada
Create Date: 2026-03-12 21:37:11.945163

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7929537df5a9'
down_revision: Union[str, None] = 'db5ece233ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('institutions_invoice_id_prefix_key'), 'institutions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('institutions_invoice_id_prefix_key'), 'institutions', ['invoice_id_prefix'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
